
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'databricks_poc'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'databricks_poc'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:     # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  databricks_poc:
    silver:
      +schema: 'poc_silver'
      materialized: view

seeds:
    quote_columns: false
    databricks_poc:
        +database: 'hive_metastore'
        poc_bronze:
            schema: 'poc_bronze'